package telas.Vender.Agendar;


import Classes.Cliente;
import Classes.Venda;
import Classes.Produto;
import Classes.Banco;
/*import java.text.DateFormat;
import java.time.format.DateTimeFormatter;*/
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alamtrindade
 */
public class Vender extends javax.swing.JFrame {

    Banco b = new Banco();

    ArrayList<Produto> produtos = b.carregaProduto();
    ArrayList<Cliente> clientes = b.CarregarCliente();

    /**
     * Creates new form Agendar
     */
    public Vender() {
        initComponents();
        carregarProduto();
        limpaTabela();
        carregarDadosComboNome();
        this.setVisible(true);

        this.tableVendas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.tableVendas.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                bRemover.setEnabled(tableVendas.getSelectedRow() >= 0);

            }

        });
    }

    public void carregarDadosComboNome() {

        ComboNome.removeAllItems();

        String cpf = this.inputCpf.getText().toLowerCase();

        if (cpf.isBlank() || cpf == null || cpf.isEmpty()) {
            for (Cliente p : clientes) {

                ComboNome.addItem(p.getNome() + "=>" + p.getCpf());

            }
        } else {
            for (Cliente p : clientes) {
                if (p.getCpf().toLowerCase().contains(cpf)) {

                    ComboNome.addItem(p.getNome() + "=>" + p.getCpf());

                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clienteCad = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        inputCpf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputTelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputEndereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ComboNome = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Cadastrado = new javax.swing.JRadioButton();
        NCadastrado = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVendas = new javax.swing.JTable();
        inputProduto = new javax.swing.JComboBox<>();
        qtd = new javax.swing.JSpinner();
        bAdicionar = new javax.swing.JButton();
        bRemover = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        valorVenda = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(84, 170, 231));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/drivefylogo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 120, 70));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Terminal de Venda");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 220, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCpfActionPerformed(evt);
            }
        });
        inputCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputCpfKeyReleased(evt);
            }
        });
        jPanel2.add(inputCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 210, 30));

        jLabel5.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(84, 170, 231));
        jLabel5.setText("Nome:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(84, 170, 231));
        jLabel6.setText("Cliente");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        jLabel7.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(84, 170, 231));
        jLabel7.setText("CPF:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        inputTelefone.setEditable(false);
        inputTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelefoneActionPerformed(evt);
            }
        });
        jPanel2.add(inputTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 140, 30));

        jLabel8.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(84, 170, 231));
        jLabel8.setText("Telefone:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        inputEndereco.setEditable(false);
        inputEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEnderecoActionPerformed(evt);
            }
        });
        jPanel2.add(inputEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 300, 30));

        jLabel9.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(84, 170, 231));
        jLabel9.setText("Cliente cadastrado:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        ComboNome.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboNomeItemStateChanged(evt);
            }
        });
        ComboNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboNomeMouseClicked(evt);
            }
        });
        ComboNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNomeActionPerformed(evt);
            }
        });
        jPanel2.add(ComboNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 280, 30));

        jLabel10.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(84, 170, 231));
        jLabel10.setText("Endereço:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        clienteCad.add(Cadastrado);
        Cadastrado.setSelected(true);
        Cadastrado.setText("Sim");
        Cadastrado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CadastradoItemStateChanged(evt);
            }
        });
        jPanel2.add(Cadastrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        clienteCad.add(NCadastrado);
        NCadastrado.setText("Não");
        jPanel2.add(NCadastrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 640, 140));

        jPanel3.setBackground(new java.awt.Color(84, 170, 231));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quantidade:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Produto:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        tableVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item", "Produto", "Valor Unitário", "Quantidade", "Total Item"
            }
        ));
        jScrollPane1.setViewportView(tableVendas);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 610, 200));

        jPanel3.add(inputProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 230, 30));

        qtd.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel3.add(qtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 110, 30));

        bAdicionar.setText("Adicionar");
        bAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdicionarActionPerformed(evt);
            }
        });
        jPanel3.add(bAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        bRemover.setText("Remover");
        bRemover.setEnabled(false);
        bRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverActionPerformed(evt);
            }
        });
        jPanel3.add(bRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 640, 330));

        jPanel5.setBackground(new java.awt.Color(84, 170, 231));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valorVenda.setFont(new java.awt.Font("Avenir Next", 3, 24)); // NOI18N
        valorVenda.setForeground(new java.awt.Color(255, 255, 255));
        valorVenda.setText("0.00");
        jPanel5.add(valorVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        btnCancelar.setForeground(new java.awt.Color(255, 51, 51));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel5.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 90, 70));

        jLabel20.setFont(new java.awt.Font("Avenir Next", 3, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("TOTAL:   R$");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnSalvar.setForeground(new java.awt.Color(0, 51, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel5.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 90, 70));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 640, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCpfActionPerformed

    private void inputTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelefoneActionPerformed

    private void inputEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEnderecoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void bAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdicionarActionPerformed
        // TODO add your handling code here:
        Produto prod = null;
        int qtd = Integer.parseInt(this.qtd.getValue().toString());
        double valor;
        String comboProd = (String) inputProduto.getSelectedItem();

        for (Produto p : produtos) {
            if (p.getTipo().equals(comboProd)) {
                prod = p;
            }
        }

        if (qtd > prod.getQuantidade()) {
            JOptionPane.showMessageDialog(rootPane, "A quantidade para venda ultrapassa o estoque atual!");
        } else if (qtd == 0) {
            JOptionPane.showMessageDialog(rootPane, "Não há quantidade para vender!");
        } else {
            valor = qtd * prod.getValor();
            addTabela(prod, qtd, valor);
        }


    }//GEN-LAST:event_bAdicionarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String CPFCliente = "";
        String Id_produto = "";
        String Nome_produto = "";
        String qtd = "";
        String preco = "";
        String totalVenda = "";
        String Data = "";
        ArrayList<Produto> alterados = new ArrayList<>();

        boolean gravar = false;

        if (Cadastrado.isSelected()) {
            if (ComboNome.getSelectedItem() == null) {
                CPFCliente = "Nao Cadastrado";
            } else {
                CPFCliente = ComboNome.getSelectedItem().toString();
            }

        } else {
            CPFCliente = "Nao Cadastrado";
        }

        DefaultTableModel tabela = (DefaultTableModel) tableVendas.getModel();
        if (tabela.getRowCount() > 0) {
            for (int i = 0; i < tabela.getRowCount(); i++) {

                for (Produto a : produtos) {
                    int b = Integer.parseInt(tabela.getValueAt(i, 0).toString());
                    if (a.getId() == b) {
                        a.setQuantidade(a.getQuantidade()-(Integer.parseInt(tabela.getValueAt(i, 3).toString())));
                        alterados.add(a);
                    }
                }

                Id_produto += "[" + tabela.getValueAt(i, 0).toString() + "]";
                Nome_produto += "[" + tabela.getValueAt(i, 1).toString() + "]";
                preco += "[" + tabela.getValueAt(i, 2).toString() + "]";
                qtd += "[" + tabela.getValueAt(i, 3).toString() + "]";

            }
            gravar = true;
        }

        if (valorVenda.getText().equals("") || valorVenda.getText().equals("0.00") || valorVenda.getText().equals("0.0") || valorVenda.getText().equals("0")) {
            gravar = false;
        } else {
            totalVenda = valorVenda.getText();
        }

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        Data = dtf.format(LocalDateTime.now());

        if (gravar) {
            Venda venda = new Venda(CPFCliente, Id_produto, Nome_produto, preco, qtd, totalVenda, Data);

            b.cadastrarVenda(venda,alterados);
            JOptionPane.showMessageDialog(rootPane, "Venda concluida com sucesso!");
            this.dispose();
        } else {

            JOptionPane.showMessageDialog(rootPane, "Não é possivel registrar a venda, verifique se os campos estão corretos!");

        }


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void bRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabela = (DefaultTableModel) tableVendas.getModel();

        tabela.removeRow(tableVendas.getSelectedRow());

        buscaatualizaTotal();


    }//GEN-LAST:event_bRemoverActionPerformed

    private void ComboNomeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboNomeItemStateChanged
        // TODO add your handling code here:
        if (ComboNome.getSelectedItem() == null) {
            inputEndereco.setText("");
            inputTelefone.setText("");

        } else {
            String[] dados = ((String) ComboNome.getSelectedItem()).split("=>");
            for (Cliente c : clientes) {
                if (c.getNome().equals(dados[0]) && c.getCpf().equals(dados[1])) {
                    inputEndereco.setText(c.getEndereco());
                    inputTelefone.setText(c.getTelefone());
                    break;

                }

            }

        }
    }//GEN-LAST:event_ComboNomeItemStateChanged

    private void ComboNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboNomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboNomeMouseClicked

    private void ComboNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNomeActionPerformed
        // TODO add your handling code here:

        if (ComboNome.getSelectedItem() == null) {
            inputEndereco.setText("");
            inputTelefone.setText("");
        } else {
            String[] dados = ((String) ComboNome.getSelectedItem()).split("=>");
            for (Cliente c : clientes) {
                if (c.getNome().equals(dados[0]) && c.getCpf().equals(dados[1])) {
                    inputEndereco.setText(c.getEndereco());
                    inputTelefone.setText(c.getTelefone());
                    break;

                }

            }

        }

    }//GEN-LAST:event_ComboNomeActionPerformed

    private void inputCpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCpfKeyReleased
        // TODO add your handling code here:
        carregarDadosComboNome();
    }//GEN-LAST:event_inputCpfKeyReleased

    private void CadastradoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CadastradoItemStateChanged
        // TODO add your handling code here:
        if (Cadastrado.isSelected()) {
            inputCpf.setEnabled(true);
            inputEndereco.setEnabled(true);
            inputTelefone.setEnabled(true);
            ComboNome.setEnabled(true);
        } else {
            inputCpf.setEnabled(false);
            inputEndereco.setEnabled(false);
            inputTelefone.setEnabled(false);
            ComboNome.setEnabled(false);
        }

    }//GEN-LAST:event_CadastradoItemStateChanged

    public void addTabela(Produto prod, int qtd, double valor) {
        DefaultTableModel tabela = (DefaultTableModel) tableVendas.getModel();

        if (!buscaTabelaAntesADD(prod, qtd, valor)) {
            Object[] row = {prod.getId(), prod.getTipo(), prod.getValor(), qtd, valor};
            tabela.addRow(row);
            double venda = Double.parseDouble(valorVenda.getText());
            venda = +valor;

            buscaatualizaTotal();
        }
    }

    public void limpaTabela() {
        DefaultTableModel tabela = (DefaultTableModel) tableVendas.getModel();
        while (tabela.getRowCount() > 0) {
            tabela.removeRow(0);
        }

    }

    public void removeTabela(Produto prod) {

    }

    public boolean buscaTabelaAntesADD(Produto prod, int qtd, double valor) {
        DefaultTableModel tabela = (DefaultTableModel) tableVendas.getModel();
        boolean atualiza = false;

        for (int i = 0; i < tabela.getRowCount(); i++) {
            if (tabela.getValueAt(i, 1).toString().equals(prod.getTipo())) {
                int qtd_atual = Integer.parseInt(tabela.getValueAt(i, 3).toString());
                qtd_atual = qtd + qtd_atual;
                if (qtd_atual > prod.getQuantidade()) {
                    JOptionPane.showMessageDialog(rootPane, "Não é possivel adicionar a quantidade estabelecida uma vez que ja ultrapassa a quantidade maxima!");
                } else {
                    double valor_atual = Double.parseDouble(tabela.getValueAt(i, 4).toString());
                    valor_atual = valor_atual + valor;
                    tabela.setValueAt(qtd_atual, i, 3);
                    tabela.setValueAt(valor_atual, i, 4);
                    buscaatualizaTotal();
                }

                atualiza = true;
                break;
            }

        }
        return atualiza;
    }

    public void buscaatualizaTotal() {
        DefaultTableModel tabela = (DefaultTableModel) tableVendas.getModel();
        double valor_atual = 0;
        for (int i = 0; i < tabela.getRowCount(); i++) {
            valor_atual += Double.parseDouble(tabela.getValueAt(i, 4).toString());
        }

        valorVenda.setText(Double.toString(valor_atual));
    }

    public void carregarProduto() {
        inputProduto.removeAllItems();

        for (Produto p : produtos) {
            if (p.getQuantidade() > 0) {
                inputProduto.addItem(p.getTipo());
            }

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cadastrado;
    private javax.swing.JComboBox<String> ComboNome;
    private javax.swing.JRadioButton NCadastrado;
    private javax.swing.JButton bAdicionar;
    private javax.swing.JButton bRemover;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup clienteCad;
    private javax.swing.JTextField inputCpf;
    private javax.swing.JTextField inputEndereco;
    private javax.swing.JComboBox<String> inputProduto;
    private javax.swing.JTextField inputTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner qtd;
    private javax.swing.JTable tableVendas;
    private javax.swing.JLabel valorVenda;
    // End of variables declaration//GEN-END:variables
}
