
import telas.Vender.Agendar.Vender;
import telasListar.ListarUsuarios;
import telasListar.ListarProdutos;
import telasListar.ListarServicos;
import telasListar.ListarVeiculos;
import telasListar.ListarClientes;
import telasListar.ListarProfissionais;
import telasListar.ListarAgenda;
import telasCadastratos.CadastrarMoto;
import telasCadastratos.CadastrarCliente;
import telas.Vender.Agendar.Agendar;
import telasCadastratos.CadastrarProduto;
import telasCadastratos.CadastrarProfissional;
import telasCadastratos.CadastrarPesados;
import telasCadastratos.CadastrarServico;
import telasCadastratos.CadastrarCarro;
import telasCadastratos.CadastrarUsuario;
import Classes.Agenda;
import Classes.Cliente;
import Classes.Servico;
import Classes.Produto;
import Classes.Profissional;
import Classes.Pesado;
import Classes.Carro;
import Classes.Banco;
import Classes.Moto;
import interfaces.iAgendamento;
import interfaces.iLogar;
import java.awt.Rectangle;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alamtrindade
 */
public class Index extends javax.swing.JFrame implements iAgendamento, iLogar {

    Banco b = new Banco();
    ArrayList<Servico> servicos = b.CarregarServico();
    ArrayList<Carro> carros = b.CarregaCarros();
    ArrayList<Moto> motos = b.CarregaMotos();
    ArrayList<Pesado> pesados = b.CarregaPesados();
    ArrayList<Cliente> clientes = b.CarregarCliente();

    ArrayList<Profissional> profissionais = b.CarregaProfissional();
    ArrayList<Produto> produtos = b.carregaProduto();

    @Override
    public Rectangle bounds() {
        return super.bounds(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    /**
     * Creates new form Index
     */
    public Index() {
        Logar();
        b.criaBanco();

        initComponents();
        carregarTabela();

    }

    public void Logar() {
        this.setVisible(false);
        new Login(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsers = new javax.swing.JMenu();
        jMenuUserCreate = new javax.swing.JMenuItem();
        jMenuUserList = new javax.swing.JMenuItem();
        jMenuProfissionals = new javax.swing.JMenu();
        jMenuProfissionalsCreate = new javax.swing.JMenuItem();
        jMenuProfissionalsList = new javax.swing.JMenuItem();
        jMenuClients = new javax.swing.JMenu();
        jMenuClientsCreate = new javax.swing.JMenuItem();
        jMenuClientsList = new javax.swing.JMenuItem();
        jMenuProducts = new javax.swing.JMenu();
        jMenuProductsCreate = new javax.swing.JMenuItem();
        jMenuProductsList = new javax.swing.JMenuItem();
        jMenuService = new javax.swing.JMenu();
        jMenuServiceCreate = new javax.swing.JMenuItem();
        jMenuServiceList = new javax.swing.JMenuItem();
        jMenuVeiculos = new javax.swing.JMenu();
        jMenuVeiculoCreate = new javax.swing.JMenu();
        jMenuCarroCreate = new javax.swing.JMenuItem();
        jMenuMotoCreate = new javax.swing.JMenuItem();
        jMenuPesadoCreate = new javax.swing.JMenuItem();
        jMenuVeiculoList = new javax.swing.JMenuItem();
        jMenuAgenda = new javax.swing.JMenu();
        jMenuPAgendaCreate = new javax.swing.JMenuItem();
        jMenuAgendaList = new javax.swing.JMenuItem();
        jVenderCreate = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(84, 170, 231));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/drivefylogo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DriveFy");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Horário", "Veículo", "Serviço", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 460));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 780, 460));

        jMenuBar1.setBackground(new java.awt.Color(84, 170, 231));
        jMenuBar1.setBorder(null);

        jMenuUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons/user.png"))); // NOI18N
        jMenuUsers.setText("Usuários");
        jMenuUsers.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jMenuUsers.setIconTextGap(1);
        jMenuUsers.setMargin(new java.awt.Insets(10, 10, 10, 30));

        jMenuUserCreate.setText("Cadastrar");
        jMenuUserCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUserCreateActionPerformed(evt);
            }
        });
        jMenuUsers.add(jMenuUserCreate);

        jMenuUserList.setText("Listar / Editar / Exluir");
        jMenuUserList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUserListActionPerformed(evt);
            }
        });
        jMenuUsers.add(jMenuUserList);

        jMenuBar1.add(jMenuUsers);

        jMenuProfissionals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons/professionals.png"))); // NOI18N
        jMenuProfissionals.setText("Profissionais");
        jMenuProfissionals.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jMenuProfissionals.setMargin(new java.awt.Insets(10, 0, 10, 30));

        jMenuProfissionalsCreate.setText("Cadastrar");
        jMenuProfissionalsCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProfissionalsCreateActionPerformed(evt);
            }
        });
        jMenuProfissionals.add(jMenuProfissionalsCreate);

        jMenuProfissionalsList.setText("Listar / Editar / Exluir");
        jMenuProfissionalsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProfissionalsListActionPerformed(evt);
            }
        });
        jMenuProfissionals.add(jMenuProfissionalsList);

        jMenuBar1.add(jMenuProfissionals);

        jMenuClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons/clientes.png"))); // NOI18N
        jMenuClients.setText("Clientes");
        jMenuClients.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jMenuClients.setMargin(new java.awt.Insets(10, 0, 10, 30));

        jMenuClientsCreate.setText("Cadastrar");
        jMenuClientsCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientsCreateActionPerformed(evt);
            }
        });
        jMenuClients.add(jMenuClientsCreate);

        jMenuClientsList.setText("Listar / Editar / Exluir");
        jMenuClientsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientsListActionPerformed(evt);
            }
        });
        jMenuClients.add(jMenuClientsList);

        jMenuBar1.add(jMenuClients);

        jMenuProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons/products.png"))); // NOI18N
        jMenuProducts.setText("Produtos");
        jMenuProducts.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jMenuProducts.setMargin(new java.awt.Insets(10, 0, 10, 30));

        jMenuProductsCreate.setText("Cadastrar");
        jMenuProductsCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProductsCreateActionPerformed(evt);
            }
        });
        jMenuProducts.add(jMenuProductsCreate);

        jMenuProductsList.setText("Listar / Editar / Exluir");
        jMenuProductsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProductsListActionPerformed(evt);
            }
        });
        jMenuProducts.add(jMenuProductsList);

        jMenuBar1.add(jMenuProducts);

        jMenuService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons/service.png"))); // NOI18N
        jMenuService.setText("Serviços");
        jMenuService.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jMenuService.setMargin(new java.awt.Insets(10, 0, 10, 30));

        jMenuServiceCreate.setText("Cadastrar");
        jMenuServiceCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuServiceCreateActionPerformed(evt);
            }
        });
        jMenuService.add(jMenuServiceCreate);

        jMenuServiceList.setText("Listar / Editar / Exluir");
        jMenuServiceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuServiceListActionPerformed(evt);
            }
        });
        jMenuService.add(jMenuServiceList);

        jMenuBar1.add(jMenuService);

        jMenuVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons/veiculos.png"))); // NOI18N
        jMenuVeiculos.setText("Veículos");
        jMenuVeiculos.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jMenuVeiculos.setMargin(new java.awt.Insets(10, 0, 10, 30));

        jMenuVeiculoCreate.setText("Cadastrar");

        jMenuCarroCreate.setText("Carro");
        jMenuCarroCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCarroCreateActionPerformed(evt);
            }
        });
        jMenuVeiculoCreate.add(jMenuCarroCreate);

        jMenuMotoCreate.setText("Moto");
        jMenuMotoCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMotoCreateActionPerformed(evt);
            }
        });
        jMenuVeiculoCreate.add(jMenuMotoCreate);

        jMenuPesadoCreate.setText("Pesado");
        jMenuPesadoCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesadoCreateActionPerformed(evt);
            }
        });
        jMenuVeiculoCreate.add(jMenuPesadoCreate);

        jMenuVeiculos.add(jMenuVeiculoCreate);

        jMenuVeiculoList.setText("Listar / Editar / Exluir");
        jMenuVeiculoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVeiculoListActionPerformed(evt);
            }
        });
        jMenuVeiculos.add(jMenuVeiculoList);

        jMenuBar1.add(jMenuVeiculos);

        jMenuAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons/Agenda.png"))); // NOI18N
        jMenuAgenda.setText("Agenda");
        jMenuAgenda.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jMenuAgenda.setMargin(new java.awt.Insets(10, 0, 10, 30));

        jMenuPAgendaCreate.setText("Agendar");
        jMenuPAgendaCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPAgendaCreateActionPerformed(evt);
            }
        });
        jMenuAgenda.add(jMenuPAgendaCreate);

        jMenuAgendaList.setText("Listar / Editar / Exluir");
        jMenuAgendaList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgendaListActionPerformed(evt);
            }
        });
        jMenuAgenda.add(jMenuAgendaList);

        jMenuBar1.add(jMenuAgenda);

        jVenderCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons/cart.png"))); // NOI18N
        jVenderCreate.setText("Vender");
        jVenderCreate.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jVenderCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVenderCreateActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Nova Venda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jVenderCreate.add(jMenuItem1);

        jMenuBar1.add(jVenderCreate);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuUserCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUserCreateActionPerformed
        new CadastrarUsuario();
    }//GEN-LAST:event_jMenuUserCreateActionPerformed

    private void jMenuUserListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUserListActionPerformed
        new ListarUsuarios();
    }//GEN-LAST:event_jMenuUserListActionPerformed

    private void jMenuProfissionalsCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProfissionalsCreateActionPerformed
        new CadastrarProfissional();
    }//GEN-LAST:event_jMenuProfissionalsCreateActionPerformed

    private void jMenuProfissionalsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProfissionalsListActionPerformed
        new ListarProfissionais();
    }//GEN-LAST:event_jMenuProfissionalsListActionPerformed

    private void jMenuClientsCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientsCreateActionPerformed
        new CadastrarCliente();
    }//GEN-LAST:event_jMenuClientsCreateActionPerformed

    private void jMenuClientsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientsListActionPerformed
        new ListarClientes();
    }//GEN-LAST:event_jMenuClientsListActionPerformed

    private void jMenuProductsCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProductsCreateActionPerformed
        new CadastrarProduto();
    }//GEN-LAST:event_jMenuProductsCreateActionPerformed

    private void jMenuProductsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProductsListActionPerformed
        new ListarProdutos();
    }//GEN-LAST:event_jMenuProductsListActionPerformed

    private void jMenuPAgendaCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPAgendaCreateActionPerformed

        if (!clientes.isEmpty() && !profissionais.isEmpty() && !servicos.isEmpty()) {

            new Agendar(this);

        } else {
            JOptionPane.showMessageDialog(rootPane, "De acordo com a base, não há clientes, profissionais ou serviços cadastrados, realize o cadastro dos itens basicos para um agendamento!");
        }
    }//GEN-LAST:event_jMenuPAgendaCreateActionPerformed

    private void jMenuAgendaListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgendaListActionPerformed
        new ListarAgenda(this);
    }//GEN-LAST:event_jMenuAgendaListActionPerformed

    private void jMenuServiceCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuServiceCreateActionPerformed
        new CadastrarServico();
    }//GEN-LAST:event_jMenuServiceCreateActionPerformed

    private void jMenuServiceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuServiceListActionPerformed
        new ListarServicos();
    }//GEN-LAST:event_jMenuServiceListActionPerformed

    private void jMenuVeiculoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVeiculoListActionPerformed
        new ListarVeiculos();
    }//GEN-LAST:event_jMenuVeiculoListActionPerformed

    private void jMenuCarroCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCarroCreateActionPerformed

        if (!clientes.isEmpty()) {
            new CadastrarCarro();
        } else {
            JOptionPane.showMessageDialog(rootPane, "De acordo com a base, não há clientes cadastrados, cadastre clientes para vincular ao veiculo que deseja cadastrar!");
        }


    }//GEN-LAST:event_jMenuCarroCreateActionPerformed

    private void jMenuMotoCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMotoCreateActionPerformed

        if (!clientes.isEmpty()) {
            new CadastrarMoto();

        } else {
            JOptionPane.showMessageDialog(rootPane, "De acordo com a base, não há clientes cadastrados, cadastre clientes para vincular ao veiculo que deseja cadastrar!");
        }
    }//GEN-LAST:event_jMenuMotoCreateActionPerformed

    private void jMenuPesadoCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesadoCreateActionPerformed

        if (!clientes.isEmpty()) {
            new CadastrarPesados();

        } else {
            JOptionPane.showMessageDialog(rootPane, "De acordo com a base, não há clientes cadastrados, cadastre clientes para vincular ao veiculo que deseja cadastrar!");
        }
    }//GEN-LAST:event_jMenuPesadoCreateActionPerformed

    private void jVenderCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVenderCreateActionPerformed

    }//GEN-LAST:event_jVenderCreateActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        boolean temProduto = false;
        if (!produtos.isEmpty() || produtos != null) {
            for (Produto p : produtos) {
                if (p.getQuantidade() > 0) {
                    temProduto = true;
                    break;
                }
            }
        }
        if (temProduto) {
            new Vender();
        } else {
            JOptionPane.showMessageDialog(rootPane, "De acordo com a base, não há produtos no estoque, cadastre ou insira mais produtos para venda!");
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void carregarTabela() {
        DefaultTableModel tabela = (DefaultTableModel) jTable1.getModel();
        ArrayList<Agenda> agendamentos = b.CarregarAgendamentos();
        while (tabela.getRowCount() > 0) {
            tabela.removeRow(0);
        }

        for (Agenda p : agendamentos) {

            String hora = p.getHora();

            String veiculo = achaVeiculopTabela(p.getPlacaVeiculo());
            String servico = achaServicopTabela(p.getServico());
            String endereco = achaClientepTabela(p.getCPFCliente());

            Object[] row = {hora, veiculo, servico, endereco};
            tabela.addRow(row);
        }

    }

    public String achaClientepTabela(String cpfCliente) {
        String dado = "";
        for (Cliente c : clientes) {
            if (c.getCpf().equals(cpfCliente)) {
                dado = c.getEndereco();
                break;
            }
        }
        return dado;
    }

    public String achaServicopTabela(String servico) {
        String dado = "";
        for (Servico c : servicos) {
            if (c.getNome_servico().equals(servico)) {
                dado = c.getNome_servico();
                break;
            }
        }
        return dado;
    }

    public String achaVeiculopTabela(String veiculo) {
        String dado = "";
        boolean achei = false;

        for (Pesado p : pesados) {
            {
                dado = p.getPlaca() + " - " + p.getModelo();
                achei = true;

                break;
            }
        }
        if (achei == false) {

            for (Carro p : carros) {
                if (p.getPlaca().equals(veiculo)) {
                    dado = p.getPlaca() + " - " + p.getModelo();
                    achei = true;

                    break;
                }
            }
        }
        if (achei == false) {
            for (Moto p : motos) {
                if (p.getPlaca().equals(veiculo)) {
                    dado = p.getPlaca() + " - " + p.getModelo();
                    achei = true;

                    break;
                }
            }
        }

        return dado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuAgenda;
    private javax.swing.JMenuItem jMenuAgendaList;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCarroCreate;
    private javax.swing.JMenu jMenuClients;
    private javax.swing.JMenuItem jMenuClientsCreate;
    private javax.swing.JMenuItem jMenuClientsList;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuMotoCreate;
    private javax.swing.JMenuItem jMenuPAgendaCreate;
    private javax.swing.JMenuItem jMenuPesadoCreate;
    private javax.swing.JMenu jMenuProducts;
    private javax.swing.JMenuItem jMenuProductsCreate;
    private javax.swing.JMenuItem jMenuProductsList;
    private javax.swing.JMenu jMenuProfissionals;
    private javax.swing.JMenuItem jMenuProfissionalsCreate;
    private javax.swing.JMenuItem jMenuProfissionalsList;
    private javax.swing.JMenu jMenuService;
    private javax.swing.JMenuItem jMenuServiceCreate;
    private javax.swing.JMenuItem jMenuServiceList;
    private javax.swing.JMenuItem jMenuUserCreate;
    private javax.swing.JMenuItem jMenuUserList;
    private javax.swing.JMenu jMenuUsers;
    private javax.swing.JMenu jMenuVeiculoCreate;
    private javax.swing.JMenuItem jMenuVeiculoList;
    private javax.swing.JMenu jMenuVeiculos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu jVenderCreate;
    // End of variables declaration//GEN-END:variables

    @Override
    public void atualizarTabela() {
        carregarTabela();
    }

    @Override
    public void loginn() {
        this.setVisible(true);
    }
}
